# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Kihong
baseurl:        ""
url:            "hxngiee.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Kihong Kim
  url:          http://hxngiee.github.io
  email:        hxngiee@gmail.com
  github:       https://github.com/hxngiee

# Custom vars
version:        3.4.1
github:
  repo:         https://https://github.com/hxngiee/hxngiee.github.io